name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Runs on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Inject API key
        run: |
          sed -i "s/__API_KEY__/${{ secrets.API_KEY }}/g" config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Publishes the entire repo